/**
 * Build a generator-ready "pack" from a composed brief variant and export it as
 * Markdown. The pack is organised by the generator's custom-mode fields so each block
 * copy-pastes straight into the matching box: Lyrics, Style of Music, Exclude
 * Styles, Weirdness %, Style Influence %. Exclusions/weirdness/influence are
 * RECOMMENDATIONS derived from the brief (clearly labelled — adjust to taste).
 * Pure + dependency-free → unit-testable; PDF is print-rendered by the client.
 */

export interface ExportPackInput {
  title: string;
  lyrics: string;
  /** The chosen variant's short style name + full style prompt. */
  styleName: string;
  stylePrompt: string;
  /** Optional brief context that tunes the recommendations. */
  mood?: string;
  theme?: string;
}

export interface ExportPack {
  title: string;
  lyrics: string;
  styleName: string;
  style: string;
  excludeStyles: string;
  weirdnessPct: number;
  styleInfluencePct: number;
}

// Styles to exclude by default for the channel's melodic/acoustic Tamil songs —
// each dropped if the chosen style actually asks for it.
const DEFAULT_EXCLUSIONS = [
  'heavy autotune',
  'EDM',
  'trap beats',
  'rap',
  'heavy metal',
  'screaming vocals',
  'distorted electric guitar',
  'dubstep',
];

const EXPERIMENTAL = /\b(experimental|fusion|modern|electronic|psychedelic|avant-?garde|glitch)\b/i;
const TRADITIONAL = /\b(traditional|classical|carnatic|devotional|folk|bhajan|lament|temple)\b/i;

/** Derive a recommended exclusion list: defaults minus anything the style wants. */
export function deriveExclusions(stylePrompt: string): string {
  const s = stylePrompt.toLowerCase();
  return DEFAULT_EXCLUSIONS.filter((x) => !s.includes(x.toLowerCase().split(' ')[0])).join(', ');
}

/** Recommended weirdness %: low for traditional, higher for experimental. */
export function deriveWeirdness(stylePrompt: string, mood = ''): number {
  const hay = `${stylePrompt} ${mood}`;
  if (EXPERIMENTAL.test(hay)) return 35;
  if (TRADITIONAL.test(hay)) return 15;
  return 20;
}

export function buildExportPack(input: ExportPackInput): ExportPack {
  const stylePrompt = (input.stylePrompt ?? '').trim();
  return {
    title: (input.title ?? '').trim() || 'Untitled',
    lyrics: (input.lyrics ?? '').trim(),
    styleName: (input.styleName ?? '').trim(),
    style: stylePrompt,
    excludeStyles: deriveExclusions(stylePrompt),
    weirdnessPct: deriveWeirdness(stylePrompt, input.mood),
    // Moderate-high: follow the described instrumentation/raga fairly closely.
    styleInfluencePct: 50,
  };
}

/** Render a export pack as copy-paste Markdown, one section per generator field. */
export function exportPackToMarkdown(pack: ExportPack): string {
  return [
    `# ${pack.title}`,
    '',
    `_Tamilagaval pack — style: ${pack.styleName || '—'}. Copy each block into the matching field._`,
    '',
    '## 🎤 Lyrics',
    '',
    pack.lyrics || '_(none)_',
    '',
    '## 🎚️ Style of Music',
    '',
    pack.style || '_(none)_',
    '',
    '## 🚫 Exclude Styles',
    '',
    pack.excludeStyles || '_(none)_',
    '',
    '## 🎛️ Weirdness',
    '',
    `${pack.weirdnessPct}%  _(recommended — adjust to taste)_`,
    '',
    '## 🌟 Style Influence',
    '',
    `${pack.styleInfluencePct}%  _(recommended — adjust to taste)_`,
    '',
    '---',
    '_Generated by Tamilagaval composer. Exclusions/weirdness/influence are starting points, not rules._',
    '',
  ].join('\n');
}

/** A safe, lowercase, dash-joined filename stem from a (possibly Tamil) title. */
export function exportFilename(title: string, ext: string): string {
  const ascii = (title || 'suno-pack')
    .normalize('NFKD')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .toLowerCase();
  return `${ascii || 'suno-pack'}.${ext}`;
}
