/**
 * Proposed literary vocabulary for the Lexicon — a REFERENCE LIST, not data.
 *
 * Generated 2026-08-15 and de-duplicated against the 1,047 headwords already in
 * the lexicon at that moment: of 833 words drafted, 252 (30%) were already
 * Raj's and were dropped. What remains is only what he did not already have.
 *
 * ⚠️ THE REGISTERS HERE ARE PROPOSALS, NOT FINDINGS. Almost everything is filed
 * `literary` deliberately — it is the mildest available claim. Only the
 * `sangam` group holds genuine Sangam-era technical terms (verse forms, the
 * anthologies, the sections of the Tolkappiyam). Calling a beautiful word
 * `sangam` because it sounds classical is the exact error that filed 1,046 of
 * the existing entries under a register nobody chose.
 *
 * ⚠️ NOTHING HERE IS IN THE DATABASE. This is a list to import from, batch by
 * batch, through /admin/lexicon → Paste list — which is what attaches the theme
 * to each word. Reading this file changes nothing.
 *
 * ⚠️ GROUPS ARE CAPPED AT 50 — the bulk endpoint's limit. A theme with more is
 * split into `theme (part n)`, because a 54-word paste is rejected whole and
 * the import silently fails.
 */

export interface ProposedWord {
  word: string;
  gloss: string;
}

export interface WordGroup {
  theme: string;
  register: string;
  words: ProposedWord[];
}

export const LEXICON_WORD_GROUPS: readonly WordGroup[] = [
  {
    theme: 'nature (part 1)',
    register: 'literary',
    words: [
      { word: 'புவனம்', gloss: 'world, earth' },
      { word: 'அவனி', gloss: 'the earth' },
      { word: 'ஞாலம்', gloss: 'the world' },
      { word: 'மேதினி', gloss: 'the earth' },
      { word: 'தாரணி', gloss: 'the earth' },
      { word: 'வையகம்', gloss: 'the world' },
      { word: 'உலகு', gloss: 'world' },
      { word: 'மண்ணுலகு', gloss: 'the earth-world' },
      { word: 'வானகம்', gloss: 'the heavens' },
      { word: 'ககனம்', gloss: 'sky' },
      { word: 'அந்தரம்', gloss: 'the middle sky' },
      { word: 'திசை', gloss: 'direction, quarter' },
      { word: 'சிமிழ்', gloss: 'small casket (of space)' },
      { word: 'பரப்பு', gloss: 'expanse' },
      { word: 'வெளி', gloss: 'open space' },
      { word: 'அகன்ற', gloss: 'vast' },
      { word: 'விரிவு', gloss: 'expanse, spreading' },
      { word: 'ஆழம்', gloss: 'depth' },
      { word: 'உயரம்', gloss: 'height' },
      { word: 'சரிவு', gloss: 'slope' },
      { word: 'மேடு', gloss: 'rise, high ground' },
      { word: 'பள்ளம்', gloss: 'hollow' },
      { word: 'சிலம்பு', gloss: 'mountain' },
      { word: 'நெய்தல்', gloss: 'seashore land' },
      { word: 'பாலை', gloss: 'arid land' },
      { word: 'புதர்', gloss: 'thicket' },
      { word: 'மரக்கூட்டம்', gloss: 'stand of trees' },
      { word: 'நிழல்', gloss: 'shade' },
      { word: 'இலைச்சருகு', gloss: 'dry leaf' },
      { word: 'தென்றல்காற்று', gloss: 'gentle south breeze' },
      { word: 'சிலிர்ப்பு', gloss: 'a thrill, bristling' },
      { word: 'குளிர்ச்சி', gloss: 'coolness' },
      { word: 'வெம்மை', gloss: 'heat' },
      { word: 'புழுதி', gloss: 'dust' },
      { word: 'மணல்', gloss: 'sand' },
      { word: 'கல்', gloss: 'stone' },
      { word: 'சரளை', gloss: 'gravel' },
      { word: 'சேற்றுநிலம்', gloss: 'marshland' },
      { word: 'வறட்சி', gloss: 'drought' },
      { word: 'பஞ்சம்', gloss: 'famine' },
      { word: 'வெள்ளப்பெருக்கு', gloss: 'flood surge' },
      { word: 'நிலநடுக்கம்', gloss: 'earthquake' },
      { word: 'எரிமலை', gloss: 'volcano' },
      { word: 'புகை', gloss: 'smoke' },
      { word: 'நெருப்பு', gloss: 'fire' },
      { word: 'தீ', gloss: 'fire' },
      { word: 'அனல்', gloss: 'burning heat' },
      { word: 'சாம்பல்', gloss: 'ash' },
      { word: 'கரி', gloss: 'charcoal' },
      { word: 'தணல்', gloss: 'embers' },
    ],
  },
  {
    theme: 'nature (part 2)',
    register: 'literary',
    words: [
      { word: 'கங்கு', gloss: 'live coal' },
      { word: 'வெடிப்பு', gloss: 'a crack, bursting' },
      { word: 'உருகல்', gloss: 'melting' },
      { word: 'உறைதல்', gloss: 'freezing' },
    ],
  },
  {
    theme: 'beauty',
    register: 'literary',
    words: [
      { word: 'சௌந்தர்யம்', gloss: 'beauty' },
      { word: 'லாவண்யம்', gloss: 'loveliness' },
      { word: 'ஒய்யாரம்', gloss: 'elegance' },
      { word: 'சிங்காரம்', gloss: 'adornment, beauty' },
      { word: 'ஆபரணம்', gloss: 'jewel' },
      { word: 'சூட்டு', gloss: 'a wreath worn' },
      { word: 'கண்ணி', gloss: 'a short garland' },
      { word: 'சேலை', gloss: 'sari' },
      { word: 'சுருள்', gloss: 'curl' },
      { word: 'பின்னல்', gloss: 'braid' },
      { word: 'நெற்றி', gloss: 'forehead' },
      { word: 'திலகம்', gloss: 'forehead mark' },
      { word: 'புருவம்', gloss: 'eyebrow' },
      { word: 'கண்', gloss: 'eye' },
      { word: 'இமை', gloss: 'eyelid' },
      { word: 'கன்னம்', gloss: 'cheek' },
      { word: 'சிரிப்பு', gloss: 'laughter' },
      { word: 'நகை', gloss: 'smile, laughter' },
      { word: 'கழுத்து', gloss: 'neck' },
      { word: 'தோள்', gloss: 'shoulder' },
      { word: 'கை', gloss: 'hand' },
      { word: 'விரல்', gloss: 'finger' },
      { word: 'அசைவு', gloss: 'movement' },
      { word: 'சாயல்', gloss: 'likeness, mien' },
      { word: 'கருமை', gloss: 'blackness' },
      { word: 'வெண்மை', gloss: 'whiteness' },
      { word: 'பொன்மை', gloss: 'goldenness' },
      { word: 'நீலம்', gloss: 'blue' },
      { word: 'செந்நிறம்', gloss: 'crimson' },
      { word: 'மாநிறம்', gloss: 'dark complexion' },
      { word: 'பொன்னிறம்', gloss: 'golden hue' },
      { word: 'மஞ்சள்', gloss: 'yellow' },
      { word: 'கபிலம்', gloss: 'tawny' },
      { word: 'புகைநிறம்', gloss: 'smoke-colour' },
      { word: 'ஒளிர்வு', gloss: 'glow' },
      { word: 'மினுமினுப்பு', gloss: 'glitter' },
      { word: 'பளபளப்பு', gloss: 'sheen' },
      { word: 'மங்கல்', gloss: 'dimming' },
      { word: 'மறைவு', gloss: 'concealment' },
      { word: 'தெளிவுநிலை', gloss: 'clearness' },
      { word: 'கலங்கல்', gloss: 'turbidity' },
      { word: 'நிழலாட்டம்', gloss: 'play of shadow' },
    ],
  },
  {
    theme: 'homeland',
    register: 'literary',
    words: [
      { word: 'நாடு', gloss: 'country' },
      { word: 'தேசம்', gloss: 'nation' },
      { word: 'பூமி', gloss: 'earth, land' },
      { word: 'ஊர்', gloss: 'town, village' },
      { word: 'கிராமம்', gloss: 'village' },
      { word: 'சிற்றூர்', gloss: 'hamlet' },
      { word: 'பட்டினம்', gloss: 'town' },
      { word: 'நகரம்', gloss: 'city' },
      { word: 'தெரு', gloss: 'street' },
      { word: 'சந்து', gloss: 'lane' },
      { word: 'பயிர்', gloss: 'crop' },
      { word: 'நெல்', gloss: 'paddy' },
      { word: 'கதிர்முற்றல்', gloss: 'ripening of grain' },
      { word: 'அறுவடை', gloss: 'harvest' },
      { word: 'களம்', gloss: 'threshing floor' },
      { word: 'ஏர்', gloss: 'plough' },
      { word: 'உழவு', gloss: 'ploughing' },
      { word: 'உழவன்', gloss: 'farmer' },
      { word: 'மாடு', gloss: 'cattle' },
      { word: 'கன்று', gloss: 'calf' },
      { word: 'மேய்ச்சல்', gloss: 'grazing' },
      { word: 'ஆயர்', gloss: 'herdsmen' },
      { word: 'இடையன்', gloss: 'shepherd' },
      { word: 'கிணறு', gloss: 'well' },
      { word: 'சேவல்', gloss: 'rooster' },
      { word: 'பனை', gloss: 'palmyra' },
      { word: 'தென்னை', gloss: 'coconut palm' },
      { word: 'அரசமரம்', gloss: 'peepul' },
      { word: 'வேம்பு', gloss: 'neem' },
      { word: 'மாமரம்', gloss: 'mango tree' },
      { word: 'கோயில்', gloss: 'temple' },
      { word: 'திருக்கோயில்', gloss: 'sacred temple' },
      { word: 'மணி', gloss: 'bell' },
      { word: 'சங்கநாதம்', gloss: 'the sound of the conch' },
      { word: 'திருவிழா', gloss: 'temple festival' },
      { word: 'தேர்', gloss: 'temple car' },
      { word: 'உடுக்கை', gloss: 'udukkai drum' },
      { word: 'வேய்ங்குழல்', gloss: 'bamboo flute' },
      { word: 'மத்தளம்', gloss: 'drum' },
    ],
  },
  {
    theme: 'language',
    register: 'literary',
    words: [
      { word: 'மொழி', gloss: 'language' },
      { word: 'தமிழ்', gloss: 'Tamil' },
      { word: 'செந்தமிழ்', gloss: 'pure/classical Tamil' },
      { word: 'முத்தமிழ்', gloss: 'the three Tamils (iyal, isai, natakam)' },
      { word: 'இயல்', gloss: 'literature' },
      { word: 'நாடகம்', gloss: 'drama' },
      { word: 'சொல்', gloss: 'word' },
      { word: 'சொற்கள்', gloss: 'words' },
      { word: 'பதம்', gloss: 'word, foot' },
      { word: 'வார்த்தை', gloss: 'word' },
      { word: 'எழுத்து', gloss: 'letter' },
      { word: 'உயிரெழுத்து', gloss: 'vowel' },
      { word: 'மெய்யெழுத்து', gloss: 'consonant' },
      { word: 'குறில்', gloss: 'short vowel' },
      { word: 'நெடில்', gloss: 'long vowel' },
      { word: 'சீர்', gloss: 'metrical foot' },
      { word: 'தளை', gloss: 'metrical linkage' },
      { word: 'பா', gloss: 'verse' },
      { word: 'பாட்டு', gloss: 'song' },
      { word: 'புலவன்', gloss: 'poet, learned one' },
      { word: 'பாவலன்', gloss: 'poet' },
      { word: 'கவிஞன்', gloss: 'poet' },
      { word: 'நூல்', gloss: 'text, book' },
      { word: 'சுவடி', gloss: 'palm-leaf manuscript' },
      { word: 'ஏடு', gloss: 'palm leaf' },
      { word: 'எழுத்தாணி', gloss: 'stylus' },
      { word: 'உரை', gloss: 'commentary' },
      { word: 'பொருள்', gloss: 'meaning' },
      { word: 'கருத்து', gloss: 'idea, purport' },
      { word: 'குறியீடு', gloss: 'symbol' },
      { word: 'படிமம்', gloss: 'image' },
      { word: 'ரசம்', gloss: 'flavour, rasa' },
      { word: 'மெய்ப்பாடு', gloss: 'the outward showing of feeling' },
    ],
  },
  {
    theme: 'sorrow',
    register: 'literary',
    words: [
      { word: 'துக்கம்', gloss: 'grief' },
      { word: 'சோகம்', gloss: 'sadness' },
      { word: 'வருத்தம்', gloss: 'regret, sorrow' },
      { word: 'வேதனை', gloss: 'pain, anguish' },
      { word: 'வலி', gloss: 'pain' },
      { word: 'நோவு', gloss: 'ache' },
      { word: 'அழுகை', gloss: 'weeping' },
      { word: 'விம்மல்', gloss: 'sobbing' },
      { word: 'ஓலம்', gloss: 'wailing' },
      { word: 'புலம்பல்', gloss: 'lamentation' },
      { word: 'அரற்றல்', gloss: 'crying out' },
      { word: 'கையறுநிலை', gloss: 'the state of helpless grief (classical genre)' },
      { word: 'சாவு', gloss: 'death' },
      { word: 'மரணம்', gloss: 'death' },
      { word: 'இழவு', gloss: 'bereavement' },
      { word: 'பிரிவாற்றாமை', gloss: 'the inability to bear separation' },
      { word: 'ஆற்றாமை', gloss: 'helpless suffering' },
      { word: 'சலனம்', gloss: 'agitation' },
      { word: 'கலக்கம்', gloss: 'disturbance of mind' },
      { word: 'அச்சம்', gloss: 'fear' },
      { word: 'பயம்', gloss: 'fear' },
      { word: 'நடுக்கம்', gloss: 'trembling' },
      { word: 'ஏமாற்றம்', gloss: 'disappointment' },
      { word: 'நிராசை', gloss: 'dashed hope' },
      { word: 'சோர்வு', gloss: 'weariness' },
      { word: 'களைப்பு', gloss: 'fatigue' },
      { word: 'சுமை', gloss: 'burden' },
    ],
  },
  {
    theme: 'emotion',
    register: 'literary',
    words: [
      { word: 'மனநிலை', gloss: 'state of mind' },
      { word: 'சலிப்பு', gloss: 'weariness, ennui' },
      { word: 'சினம்', gloss: 'anger' },
      { word: 'கோபம்', gloss: 'anger' },
      { word: 'ஆத்திரம்', gloss: 'fury' },
      { word: 'வெறுப்பு', gloss: 'hatred' },
      { word: 'பொறாமை', gloss: 'envy' },
      { word: 'பெருமிதம்', gloss: 'pride, dignity' },
      { word: 'தன்மானம்', gloss: 'self-respect' },
      { word: 'அவமானம்', gloss: 'humiliation' },
      { word: 'வெட்கம்', gloss: 'shame' },
      { word: 'குற்றவுணர்வு', gloss: 'guilt' },
      { word: 'நன்றி', gloss: 'gratitude' },
      { word: 'கடன்பாடு', gloss: 'indebtedness' },
      { word: 'நம்பகம்', gloss: 'trustworthiness' },
      { word: 'சந்தேகம்', gloss: 'doubt' },
      { word: 'தயக்கம்', gloss: 'hesitation' },
      { word: 'துணிச்சல்', gloss: 'daring' },
      { word: 'அதிர்ச்சி', gloss: 'shock' },
      { word: 'வியப்பு', gloss: 'wonder' },
      { word: 'ஆச்சரியம்', gloss: 'astonishment' },
      { word: 'பரவசநிலை', gloss: 'state of ecstasy' },
      { word: 'கிளர்ச்சி', gloss: 'excitement' },
      { word: 'அமைதியின்மை', gloss: 'restlessness' },
      { word: 'தவிப்புநிலை', gloss: 'state of anguish' },
      { word: 'ஏமாற்று', gloss: 'deception' },
      { word: 'நயவஞ்சகம்', gloss: 'treachery' },
    ],
  },
  {
    theme: 'rain',
    register: 'literary',
    words: [
      { word: 'பெருமழை', gloss: 'heavy rain' },
      { word: 'சிறுதூறல்', gloss: 'light drizzle' },
      { word: 'பொழிவு', gloss: 'downpour, outpouring' },
      { word: 'வர்ஷம்', gloss: 'rain' },
      { word: 'மூடுபனி', gloss: 'thick mist' },
      { word: 'கருமுகில்', gloss: 'black cloud' },
      { word: 'இடி', gloss: 'thunder' },
      { word: 'கார்காலம்', gloss: 'the rainy season' },
      { word: 'புயல்', gloss: 'storm' },
      { word: 'சூறாவளி', gloss: 'whirlwind' },
      { word: 'வாடை', gloss: 'north wind' },
      { word: 'கோடை', gloss: 'summer; hot wind' },
      { word: 'வெப்பம்', gloss: 'heat' },
      { word: 'குளிர்', gloss: 'cold' },
      { word: 'ஈரம்', gloss: 'moisture' },
      { word: 'நனைவு', gloss: 'being drenched' },
      { word: 'சொட்டு', gloss: 'a drop' },
      { word: 'வடிதல்', gloss: 'trickling down' },
      { word: 'சுனை', gloss: 'spring, pool' },
      { word: 'ஓடை', gloss: 'brook' },
      { word: 'கால்வாய்', gloss: 'channel' },
      { word: 'வாய்க்கால்', gloss: 'irrigation channel' },
      { word: 'ஏரி', gloss: 'lake' },
      { word: 'கயம்', gloss: 'deep pool' },
      { word: 'மடு', gloss: 'deep water' },
      { word: 'சேறு', gloss: 'mire' },
    ],
  },
  {
    theme: 'flowers',
    register: 'literary',
    words: [
      { word: 'பூங்கொடி', gloss: 'flowering creeper' },
      { word: 'மொட்டு', gloss: 'bud' },
      { word: 'இதழ்', gloss: 'petal' },
      { word: 'தாது', gloss: 'pollen' },
      { word: 'தேன்', gloss: 'honey, nectar' },
      { word: 'மது', gloss: 'nectar' },
      { word: 'வாசம்', gloss: 'scent' },
      { word: 'கமழ்', gloss: 'fragrance, to be fragrant' },
      { word: 'செண்பகம்', gloss: 'champak' },
      { word: 'பிச்சி', gloss: 'wild jasmine' },
      { word: 'குறிஞ்சிப்பூ', gloss: 'kurinji flower' },
      { word: 'காந்தள்', gloss: 'glory lily' },
      { word: 'செங்காந்தள்', gloss: 'red glory lily' },
      { word: 'குவளை', gloss: 'waterlily' },
      { word: 'ஆம்பல்', gloss: 'white waterlily' },
      { word: 'செந்தாமரை', gloss: 'red lotus' },
      { word: 'கமலம்', gloss: 'lotus' },
      { word: 'வண்டு', gloss: 'beetle, bee' },
      { word: 'தும்பி', gloss: 'dragonfly, bee' },
      { word: 'மகரந்தச்சேர்க்கை', gloss: 'pollination' },
      { word: 'நந்தவனம்', gloss: 'pleasure garden' },
      { word: 'மலர்மஞ்சம்', gloss: 'bed of flowers' },
      { word: 'கொத்து', gloss: 'cluster' },
      { word: 'துளிர்', gloss: 'new sprout' },
      { word: 'பசுங்கிளை', gloss: 'green branch' },
      { word: 'அடிமரம்', gloss: 'trunk' },
    ],
  },
  {
    theme: 'sea',
    register: 'literary',
    words: [
      { word: 'கடலம்மா', gloss: 'mother sea' },
      { word: 'பௌவம்', gloss: 'sea' },
      { word: 'வாரிதி', gloss: 'ocean' },
      { word: 'திரை', gloss: 'wave, curtain' },
      { word: 'நுரை', gloss: 'foam' },
      { word: 'சங்கு', gloss: 'conch' },
      { word: 'முத்து', gloss: 'pearl' },
      { word: 'பவளம்', gloss: 'coral' },
      { word: 'சிப்பி', gloss: 'oyster shell' },
      { word: 'துறை', gloss: 'landing place, ghat' },
      { word: 'படகு', gloss: 'boat' },
      { word: 'தோணி', gloss: 'small boat' },
      { word: 'பாய்மரம்', gloss: 'mast' },
      { word: 'துடுப்பு', gloss: 'oar' },
      { word: 'கலம்', gloss: 'ship' },
      { word: 'நங்கூரம்', gloss: 'anchor' },
      { word: 'சுழி', gloss: 'whirlpool' },
      { word: 'ஓதம்', gloss: 'tide' },
      { word: 'வெள்ளம்', gloss: 'flood' },
      { word: 'நதி', gloss: 'river' },
      { word: 'யாறு', gloss: 'river' },
      { word: 'பேராறு', gloss: 'great river' },
      { word: 'கழிமுகம்', gloss: 'estuary' },
      { word: 'நீரோட்டம்', gloss: 'current' },
      { word: 'சலசலப்பு', gloss: 'murmur of water' },
    ],
  },
  {
    theme: 'time',
    register: 'literary',
    words: [
      { word: 'காலம்', gloss: 'time' },
      { word: 'நேரம்', gloss: 'time, hour' },
      { word: 'கணம்', gloss: 'moment' },
      { word: 'நொடி', gloss: 'second' },
      { word: 'வினாடி', gloss: 'instant' },
      { word: 'யுகம்', gloss: 'age, epoch' },
      { word: 'ஊழி', gloss: 'aeon' },
      { word: 'நூற்றாண்டு', gloss: 'century' },
      { word: 'ஆண்டு', gloss: 'year' },
      { word: 'மாதம்', gloss: 'month' },
      { word: 'வாரம்', gloss: 'week' },
      { word: 'நாள்', gloss: 'day' },
      { word: 'பருவம்', gloss: 'season' },
      { word: 'முதுவேனில்', gloss: 'late summer' },
      { word: 'கூதிர்', gloss: 'cool season' },
      { word: 'முன்பனி', gloss: 'early dew season' },
      { word: 'பின்பனி', gloss: 'late dew season' },
      { word: 'வசந்தம்', gloss: 'spring' },
      { word: 'நினைவுக்காலம்', gloss: 'the time of remembering' },
      { word: 'கடந்தது', gloss: 'that which has passed' },
      { word: 'நிகழ்வு', gloss: 'the present, an event' },
      { word: 'வருங்காலம்', gloss: 'the time to come' },
      { word: 'நிரந்தரம்', gloss: 'permanence' },
      { word: 'தற்காலிகம்', gloss: 'the temporary' },
    ],
  },
  {
    theme: 'movement',
    register: 'literary',
    words: [
      { word: 'நடத்தல்', gloss: 'walking' },
      { word: 'ஓட்டம்', gloss: 'running' },
      { word: 'தாவல்', gloss: 'leaping' },
      { word: 'பறத்தல்', gloss: 'flying' },
      { word: 'நீந்தல்', gloss: 'swimming' },
      { word: 'ஊர்தல்', gloss: 'creeping' },
      { word: 'சுழற்சி', gloss: 'whirling' },
      { word: 'அசைதல்', gloss: 'swaying' },
      { word: 'ஆடல்', gloss: 'dance' },
      { word: 'கூத்து', gloss: 'dance, performance' },
      { word: 'நர்த்தனம்', gloss: 'dance' },
      { word: 'சிலம்பாட்டம்', gloss: 'stick-dance' },
      { word: 'நடனம்', gloss: 'dance' },
      { word: 'பாய்ச்சல்', gloss: 'a bound' },
      { word: 'வீழ்ச்சி', gloss: 'a fall' },
      { word: 'எழுச்சிநிலை', gloss: 'rising state' },
      { word: 'திரும்பல்', gloss: 'turning back' },
      { word: 'நிற்றல்', gloss: 'standing' },
      { word: 'அமர்தல்', gloss: 'sitting' },
      { word: 'சாய்தல்', gloss: 'leaning' },
      { word: 'வளைதல்', gloss: 'bending' },
      { word: 'நெளிவு', gloss: 'winding' },
      { word: 'சுருங்கல்', gloss: 'shrinking' },
      { word: 'விரிதல்', gloss: 'spreading open' },
    ],
  },
  {
    theme: 'philosophy',
    register: 'literary',
    words: [
      { word: 'மெய்', gloss: 'truth' },
      { word: 'பொய்', gloss: 'falsehood' },
      { word: 'நல்லது', gloss: 'the good' },
      { word: 'தீது', gloss: 'evil' },
      { word: 'புண்ணியம்', gloss: 'merit' },
      { word: 'கருமம்', gloss: 'action, karma' },
      { word: 'பயன்', gloss: 'fruit, result' },
      { word: 'விளைவு', gloss: 'consequence' },
      { word: 'துறவு', gloss: 'renunciation' },
      { word: 'பற்றின்மை', gloss: 'non-attachment' },
      { word: 'மாயை', gloss: 'illusion' },
      { word: 'நிலையாமை', gloss: 'impermanence' },
      { word: 'அழிவு', gloss: 'destruction' },
      { word: 'நிலைபேறு', gloss: 'permanence' },
      { word: 'முக்தி', gloss: 'liberation' },
      { word: 'விடுதலை', gloss: 'freedom' },
      { word: 'சரணம்', gloss: 'refuge' },
      { word: 'பக்தி', gloss: 'devotion' },
      { word: 'வழிபாடு', gloss: 'worship' },
      { word: 'தியானம்', gloss: 'meditation' },
      { word: 'மௌனம்', gloss: 'silence' },
      { word: 'அமைதிநிலை', gloss: 'state of stillness' },
    ],
  },
  {
    theme: 'family',
    register: 'literary',
    words: [
      { word: 'வீடு', gloss: 'house' },
      { word: 'கூரை', gloss: 'roof' },
      { word: 'வாசல்', gloss: 'threshold, doorway' },
      { word: 'திண்ணை', gloss: 'the front platform of a house' },
      { word: 'முற்றம்', gloss: 'courtyard' },
      { word: 'அடுப்பு', gloss: 'hearth' },
      { word: 'பந்தம்', gloss: 'bond' },
      { word: 'கட்டு', gloss: 'tie' },
      { word: 'சேய்', gloss: 'child' },
      { word: 'மகன்', gloss: 'son' },
      { word: 'மகள்', gloss: 'daughter' },
      { word: 'பிள்ளை', gloss: 'child' },
      { word: 'குழந்தை', gloss: 'infant' },
      { word: 'சிறுவன்', gloss: 'boy' },
      { word: 'சிறுமி', gloss: 'girl' },
      { word: 'இளமை', gloss: 'youth' },
      { word: 'பாலியம்', gloss: 'childhood' },
      { word: 'சிறுவயது', gloss: 'young age' },
      { word: 'விளையாட்டு', gloss: 'play' },
      { word: 'சிரிப்பொலி', gloss: 'the sound of laughter' },
      { word: 'கேண்மை', gloss: 'friendship' },
    ],
  },
  {
    theme: 'hope',
    register: 'literary',
    words: [
      { word: 'எதிர்காலம்', gloss: 'the future' },
      { word: 'விடியல்நம்பிக்கை', gloss: 'hope of a dawn' },
      { word: 'மறம்', gloss: 'martial valour' },
      { word: 'ஆண்மை', gloss: 'manliness, prowess' },
      { word: 'திண்மை', gloss: 'firmness' },
      { word: 'விடாமுயற்சி', gloss: 'perseverance' },
      { word: 'முயற்சி', gloss: 'effort' },
      { word: 'உழைப்பு', gloss: 'labour' },
      { word: 'வெற்றி', gloss: 'victory' },
      { word: 'தோல்வி', gloss: 'defeat' },
      { word: 'சவால்', gloss: 'challenge' },
      { word: 'போராட்டம்', gloss: 'struggle' },
      { word: 'எழுச்சி', gloss: 'rising up' },
      { word: 'புத்துயிர்', gloss: 'new life' },
      { word: 'மறுமலர்ச்சி', gloss: 'renaissance, reblossoming' },
      { word: 'மாற்றம்', gloss: 'change' },
      { word: 'கனவுலகு', gloss: 'dream-world' },
      { word: 'இலட்சியம்', gloss: 'ideal' },
      { word: 'குறிக்கோள்', gloss: 'goal' },
      { word: 'பாதைவகுத்தல்', gloss: 'path-making' },
      { word: 'சாதனை', gloss: 'achievement' },
    ],
  },
  {
    theme: 'life',
    register: 'literary',
    words: [
      { word: 'ஜீவன்', gloss: 'life' },
      { word: 'சுவாசம்', gloss: 'breath' },
      { word: 'மூச்சு', gloss: 'breath' },
      { word: 'சித்தம்', gloss: 'mind, will' },
      { word: 'ஆன்மா', gloss: 'soul' },
      { word: 'புறம்', gloss: 'the exterior' },
      { word: 'வாழ்க்கை', gloss: 'life' },
      { word: 'பிறப்பு', gloss: 'birth' },
      { word: 'வளர்ச்சி', gloss: 'growth' },
      { word: 'முதிர்ச்சி', gloss: 'maturity' },
      { word: 'மூப்பு', gloss: 'old age' },
      { word: 'நரை', gloss: 'grey hair' },
      { word: 'சுருக்கம்', gloss: 'wrinkle' },
      { word: 'முடிவு', gloss: 'end' },
      { word: 'பாதை', gloss: 'path' },
      { word: 'திசைமாற்றம்', gloss: 'change of direction' },
      { word: 'விதி', gloss: 'fate' },
      { word: 'ஊழ்', gloss: 'destiny' },
      { word: 'தலைவிதி', gloss: 'destiny' },
      { word: 'வாய்ப்பு', gloss: 'opportunity' },
    ],
  },
  {
    theme: 'love',
    register: 'literary',
    words: [
      { word: 'காமம்', gloss: 'desire' },
      { word: 'விருப்பு', gloss: 'liking' },
      { word: 'நாட்டம்', gloss: 'inclination' },
      { word: 'ஈடுபாடு', gloss: 'attachment' },
      { word: 'இணை', gloss: 'pair, mate' },
      { word: 'துணை', gloss: 'companion' },
      { word: 'கூட்டு', gloss: 'union' },
      { word: 'புணர்ச்சி', gloss: 'union, joining' },
      { word: 'கலவி', gloss: 'union' },
      { word: 'சேர்க்கை', gloss: 'coming together' },
      { word: 'தழுவல்', gloss: 'embrace' },
      { word: 'அணைப்பு', gloss: 'embrace' },
      { word: 'முத்தம்', gloss: 'kiss' },
      { word: 'கூச்சம்', gloss: 'shyness' },
      { word: 'சிணுங்கல்', gloss: 'coy murmuring' },
      { word: 'ஊடல்தீர்த்தல்', gloss: 'reconciliation' },
      { word: 'புலவி', gloss: 'sulking' },
      { word: 'கலகம்', gloss: 'quarrel' },
      { word: 'சமாதானம்', gloss: 'reconciliation' },
    ],
  },
  {
    theme: 'sangam',
    register: 'sangam',
    words: [
      { word: 'வெண்பா', gloss: 'venpa verse form' },
      { word: 'கலிப்பா', gloss: 'kalippa verse form' },
      { word: 'வஞ்சிப்பா', gloss: 'vanchippa verse form' },
      { word: 'ஆசிரியப்பா', gloss: 'asiriyappa verse form' },
      { word: 'பொருளதிகாரம', gloss: 'the section on subject matter' },
      { word: 'எழுத்ததிகாரம்', gloss: 'the section on letters' },
      { word: 'சொல்லதிகாரம்', gloss: 'the section on words' },
      { word: 'பத்துப்பாட்டு', gloss: 'the Ten Idylls' },
      { word: 'எட்டுத்தொகை', gloss: 'the Eight Anthologies' },
      { word: 'பதினெண்கீழ்க்கணக்கு', gloss: 'the Eighteen Minor Works' },
      { word: 'சங்கம்', gloss: 'the academy of Tamil poets' },
      { word: 'புலமை', gloss: 'scholarship' },
      { word: 'கம்பளை', gloss: 'assembly of the learned' },
      { word: 'வண்ணம்', gloss: 'metrical colour, mode' },
      { word: 'தூக்கு', gloss: 'metrical measure' },
      { word: 'அளபு', gloss: 'measure of a sound' },
    ],
  },
  {
    theme: 'sun',
    register: 'literary',
    words: [
      { word: 'ஆதவன்', gloss: 'the sun' },
      { word: 'சூரியன்', gloss: 'the sun' },
      { word: 'இரவி', gloss: 'the sun' },
      { word: 'பானு', gloss: 'the sun' },
      { word: 'கதிர்', gloss: 'ray, beam' },
      { word: 'கிரணம்', gloss: 'ray' },
      { word: 'வெப்பக்கதிர்', gloss: 'hot ray' },
      { word: 'சுடர்', gloss: 'flame, radiance' },
      { word: 'ஒளி', gloss: 'light' },
      { word: 'ஜோதி', gloss: 'flame of light' },
      { word: 'தீபம்', gloss: 'lamp' },
      { word: 'விளக்கு', gloss: 'lamp' },
      { word: 'மங்கலொளி', gloss: 'auspicious light' },
      { word: 'வெண்ணொளி', gloss: 'white light' },
      { word: 'நிழலொளி', gloss: 'dappled light' },
    ],
  },
  {
    theme: 'birds',
    register: 'literary',
    words: [
      { word: 'புள்', gloss: 'bird' },
      { word: 'குருவி', gloss: 'sparrow' },
      { word: 'தூக்கணாங்குருவி', gloss: 'weaver bird' },
      { word: 'புறா', gloss: 'dove' },
      { word: 'வானம்பாடி', gloss: 'skylark' },
      { word: 'கடல்புள்', gloss: 'sea bird' },
      { word: 'கொக்கு', gloss: 'crane' },
      { word: 'நாரை', gloss: 'stork' },
      { word: 'மரங்கொத்தி', gloss: 'woodpecker' },
      { word: 'இறகு', gloss: 'feather' },
      { word: 'கூடு', gloss: 'nest' },
      { word: 'சிலம்பல்', gloss: 'birdsong' },
      { word: 'கூவல்', gloss: 'call, crying out' },
      { word: 'ராகம்', gloss: 'raga' },
      { word: 'சுருதி', gloss: 'pitch, tonic' },
    ],
  },
  {
    theme: 'father',
    register: 'literary',
    words: [
      { word: 'அப்பன்', gloss: 'father' },
      { word: 'பெற்றோன்', gloss: 'the father who begot' },
      { word: 'ஈன்றோன்', gloss: 'begetter' },
      { word: 'முன்னோர்', gloss: 'forebears' },
      { word: 'பாட்டன்', gloss: 'grandfather' },
      { word: 'பாட்டி', gloss: 'grandmother' },
      { word: 'மூதாதை', gloss: 'ancestor' },
      { word: 'வழிவழி', gloss: 'through generations' },
      { word: 'பரம்பரை', gloss: 'lineage' },
      { word: 'குலம்', gloss: 'clan' },
      { word: 'வம்சம்', gloss: 'lineage' },
      { word: 'பரிவட்டம்', gloss: 'honour-cloth' },
      { word: 'கட்டளை', gloss: 'command' },
      { word: 'நிழல்தந்தவன்', gloss: 'he who gave shade' },
      { word: 'தோள்கொடுத்தல', gloss: 'to lend a shoulder' },
    ],
  },
  {
    theme: 'mother',
    register: 'literary',
    words: [
      { word: 'தாய்', gloss: 'mother' },
      { word: 'அம்மை', gloss: 'mother' },
      { word: 'ஈன்றவள்', gloss: 'she who bore' },
      { word: 'பெற்றவள்', gloss: 'she who gave birth' },
      { word: 'மடி', gloss: 'lap' },
      { word: 'கருவறை', gloss: 'womb' },
      { word: 'கரு', gloss: 'embryo' },
      { word: 'பாலூட்டல்', gloss: 'suckling' },
      { word: 'தாலாட்டு', gloss: 'lullaby' },
      { word: 'சீராட்டு', gloss: 'fond nurturing' },
      { word: 'தொட்டில்', gloss: 'cradle' },
      { word: 'முலைப்பால்', gloss: 'mother\'s milk' },
      { word: 'வாஞ்சை', gloss: 'fond affection' },
      { word: 'பரிதாபம்', gloss: 'pity' },
    ],
  },
  {
    theme: 'longing',
    register: 'literary',
    words: [
      { word: 'தாபம்', gloss: 'burning desire' },
      { word: 'பரிதவிப்பு', gloss: 'pining' },
      { word: 'விரகம்', gloss: 'the pain of separation' },
      { word: 'ஒற்றுமையின்மை', gloss: 'apartness' },
      { word: 'அயலான்', gloss: 'a stranger' },
      { word: 'வேறுபாடு', gloss: 'difference, estrangement' },
      { word: 'இழப்பு', gloss: 'loss' },
      { word: 'வெறுமை', gloss: 'emptiness' },
      { word: 'வெற்றிடம்', gloss: 'void' },
      { word: 'ஞாபகம்', gloss: 'recollection' },
      { word: 'மறதி', gloss: 'forgetting' },
      { word: 'நினைவுக்கீற்று', gloss: 'a streak of memory' },
      { word: 'கடந்த காலம்', gloss: 'the past' },
    ],
  },
  {
    theme: 'joy',
    register: 'literary',
    words: [
      { word: 'மகிழ்ச்சி', gloss: 'joy' },
      { word: 'சந்தோஷம்', gloss: 'happiness' },
      { word: 'சுகம்', gloss: 'comfort, ease' },
      { word: 'திருப்தி', gloss: 'contentment' },
      { word: 'சாந்தம்', gloss: 'serenity' },
      { word: 'தேறுதல்', gloss: 'solace' },
      { word: 'உற்சாகம்', gloss: 'enthusiasm' },
      { word: 'ஊக்கம்', gloss: 'zeal' },
      { word: 'துள்ளல்', gloss: 'leaping (with joy)' },
      { word: 'கொண்டாட்டம்', gloss: 'celebration' },
      { word: 'விழா', gloss: 'festival' },
    ],
  },
  {
    theme: 'night',
    register: 'literary',
    words: [
      { word: 'இரவு', gloss: 'night' },
      { word: 'நடுயாமம்', gloss: 'midnight' },
      { word: 'இருள்', gloss: 'darkness' },
      { word: 'கருக்கல்', gloss: 'dusk-dark' },
      { word: 'அமாவாசை', gloss: 'new-moon night' },
      { word: 'நிசி', gloss: 'night' },
      { word: 'துயில்', gloss: 'sleep' },
      { word: 'விழிப்பு', gloss: 'wakefulness' },
      { word: 'அயர்வு', gloss: 'drowsiness' },
    ],
  },
  {
    theme: 'moon',
    register: 'literary',
    words: [
      { word: 'சந்திரன்', gloss: 'moon' },
      { word: 'வெண்ணிலா', gloss: 'white moonlight' },
      { word: 'முழுநிலா', gloss: 'full moon' },
      { word: 'கலை', gloss: 'digit of the moon; art' },
      { word: 'வானமதி', gloss: 'moon of the sky' },
      { word: 'நட்சத்திரம்', gloss: 'star' },
      { word: 'மீன்', gloss: 'star (in the sky)' },
      { word: 'அந்திவெள்ளி', gloss: 'evening star' },
    ],
  },
  {
    theme: 'dawn',
    register: 'literary',
    words: [
      { word: 'காலை', gloss: 'morning' },
      { word: 'உதயம்', gloss: 'rising' },
      { word: 'புலர்தல்', gloss: 'dawning' },
      { word: 'கீழ்வானம்', gloss: 'the eastern sky' },
      { word: 'செம்வானம்', gloss: 'red sky' },
    ],
  },
  {
    theme: 'dusk',
    register: 'literary',
    words: [
      { word: 'மாலை', gloss: 'evening' },
      { word: 'அஸ்தமனம்', gloss: 'sunset' },
      { word: 'சாயங்காலம்', gloss: 'late afternoon, evening' },
      { word: 'அந்திமயக்கம்', gloss: 'twilight dimness' },
      { word: 'இருள்சாய்வு', gloss: 'the falling of darkness' },
    ],
  },
];

/** Total proposed words across every group. */
export const LEXICON_WORD_COUNT = LEXICON_WORD_GROUPS.reduce((n, g) => n + g.words.length, 0);
